### ISSUE TITLE
Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by liujhfly** [WingGao/mpvue-ts-demo#16]
npm install之后 npm run dev项目正常启动，在微信开发者工具中出现以下错误：
thirdScriptError 
 sdk uncaught third Error 
 Reflect.getMetadata is not a function 
 TypeError: Reflect.getMetadata is not a function
    at http://127.0.0.1:61404/appservice/static/js/vendor.js:5659:32
    at __decorate (http://127.0.0.1:61404/appservice/static/js/pages/index/main.js:366:60)
    at http://127.0.0.1:61404/appservice/static/js/pages/index/main.js:388:7
    at Object._ (http://127.0.0.1:61404/appservice/static/js/pages/index/main.js:396:6)
    at __webpack_require__ (http://127.0.0.1:61404/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:61404/appservice/static/js/pages/index/main.js:24:104)
    at __webpack_require__ (http://127.0.0.1:61404/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:61404/appservice/static/js/pages/index/main.js:420:83)
    at __webpack_require__ (http://127.0.0.1:61404/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:61404/appservice/static/js/pages/index/main.js:277:104)

请问会是什么原因？

**Comment by linfan68** [comment]
我之前遇到这个问题好像是升级typescript 3.0的时候遇到的。应该是vue-class-decorator用到了reflect。workaround是在定义@Prop的时候把type提供，这样代码就不会去用reflector猜类型了：

```ts
  @Prop({type: String, default: '1' }) text: string
```

**Comment by liujhfly** [comment]
> 我之前遇到这个问题好像是升级typescript 3.0的时候遇到的。应该是vue-class-decorator用到了reflect。workaround是在定义@prop的时候把type提供，这样代码就不会去用reflector猜类型了：
> 
> ```ts
>   @Prop({type: String, default: '1' }) text: string
> ```
看得不是太懂呢，还能告知我应该怎么解决这个问题呢
