### ISSUE TITLE
module "common/manifest.js" is not defined

### ISSUE THREAD

**Issue by liujhfly** [WingGao/mpvue-ts-demo#17]
删除demo, 重新下载，再解压
npm i
npm run dev
后以下错误：
VM277:1 thirdScriptError 
 sdk uncaught third Error 
 module "common/manifest.js" is not defined 
 Error: module "common/manifest.js" is not defined
    at require (http://127.0.0.1:61404/appservice/__dev__/WAService.js:23:13423)
    at http://127.0.0.1:61404/appservice/__dev__/WAService.js:23:13171
    at http://127.0.0.1:61404/appservice/pages/index/main.js:3:1
    at require (http://127.0.0.1:61404/appservice/__dev__/WAService.js:23:13564)
    at <anonymous>:6:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:61404/appservice/appservice?t=1539488179497:1190:23)

**Comment by linfan68** [comment]
@WingGao 建议把yarn.lock之类的package版本文件传一份上来，要不然各种包一升级老会出这种问题

**Comment by WingGao** [comment]
好的，多谢。
