### ISSUE TITLE
Cannot read property 'template' of undefined

### ISSUE THREAD

**Issue by okou19900722** [WingGao/mpvue-ts-demo#20]
上周我直接clone下来执行npm run dev完全没有问题，只有执行npm run build时有问题。
这周再来就抛异常了。

```
H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\mpvue-loader\lib\mp-compiler\util.js:19
  const filePath = `/${resolveSrc(context, file)}.${fileExt.template}`
                                                            ^
TypeError: Cannot read property 'template' of undefined
    at getCompInfo (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\mpvue-loader\lib\mp-compiler\util.js:19:61)
    at createPageMPML (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\mpvue-loader\lib\mp-compiler\index.js:41:30)
    at resolve (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\mpvue-loader\lib\mp-compiler\index.js:196:9)
    at onResolve (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at innerCallback (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\Resolver.js:130:22)
    at callbackWrapper (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\tapable\lib\Tapable.js:347:15
    at H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:39:22
    at callbackWrapper (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at innerCallback (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\Resolver.js:130:22)
    at callbackWrapper (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\tapable\lib\Tapable.js:347:15
    at innerCallback (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\Resolver.js:130:22)
    at callbackWrapper (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\tapable\lib\Tapable.js:347:15
    at resolver.doResolve.createInnerCallback (H:\okou\versionControl\git\mpvue-ts-demo2\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:41:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mpvue-ts-demo@1.0.0 dev: `cross-env node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mpvue-ts-demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by okou19900722** [comment]
![image](https://user-images.githubusercontent.com/13762092/52158811-02e69200-26d7-11e9-987e-234967e2c94f.png)

这是微信开发者工作里的异常

**Comment by okou19900722** [comment]
而且通过浏览器访问 `localhost:7100` ，显示 `Cannot GET /`

**Comment by WingGao** [comment]
嗯，这是因为mpvue更新了，目前已解决，你合并下吧，多谢。
https://github.com/WingGao/mpvue-ts-demo/commit/4df7c608617055c7a8ced73a17c2a8017ee17be1

**Comment by okou19900722** [comment]
感谢，

**Comment by AplogizeDear** [comment]
为啥我更新之后还在报这个错误
