### ISSUE TITLE
感谢！能否说明一下需要做哪些更改？

### ISSUE THREAD

**Issue by linfan68** [WingGao/mpvue-ts-demo#6]
感谢您提供的Typescript项目！
我想按照您提供的例子将一个刚生成的mpvue项目加入typescript支持，整个过程很不顺利……
能否大概说一下您在加入ts支持的时候做了哪些事情？我看到的有：
1. 在.vue 的<script> 里面加上lang="ts"
2. 在view-loader.conf.js里面加入ts: [... 部分
3. 在webpack.base.conf.js里面加入test: /\.tsx?$/, 部分
4. 加入vue-shim.d.ts
5. 加入tsconfig.json
6. package.json里面加入typescript

但是现在我尝试把一个page变成ts的page，结果是dist/目录里面没有这个page了...
.ts文件里面也对Component和Vue报错

**Comment by WingGao** [comment]
大致如下
* `mpvue-loader`请使用最新的
* 然后`.vue`对应的`script`文件格式如下 https://github.com/WingGao/mpvue-ts-demo/blob/dev/src/pages/index/index.ts
* 基本就这么点了，大致组件格式可以拷贝这个 https://github.com/WingGao/mpvue-ts-demo/tree/dev/src/pages/index

**Comment by linfan68** [comment]
感谢~
另外还有一个问题（不好意思本人是小程序/Vue新手……）
我尝试在compoent/card.vue里面用class 风格的component定义方法（https://github.com/vuejs/vue-class-component）但是貌似不行。
总是在编译的时候出这个错：
```
[at-loader]: Child process failed to process the request:  TypeError: Cannot read property 'externalModuleIndicator' of undefined
    at Object.isExternalModule (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\typescript\lib\typescript.js:13733:21)
    at Object.getAllDependencies (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\typescript\lib\typescript.js:75788:46)
    at Object.getAllDependencies (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\typescript\lib\typescript.js:76133:80)
    at processEmit (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\checker\runtime.ts:451:24)
    at E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\checker\runtime.ts:602:6
    at Object.send (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\checker\runtime.ts:48:6)
    at Checker.req (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\checker\checker.ts:100:15)
    at Checker.emitFile (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\checker\checker.ts:105:15)    at transform (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\index.ts:132:26)
    at transformationFunction (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\index.ts:74:40)
    at Object.cache (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\cache.ts:104:10)
    at compiler (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\index.ts:77:21)
    at Object.loader (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\awesome-typescript-loader\src\index.ts:16:12)
    at LOADER_EXECUTION (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (E:\src\PT\wgpt2\mpvue\pt-mp\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
```

**Comment by linfan68** [comment]
@WingGao 是不是你发的这个Issue呢？
https://github.com/s-panferov/awesome-typescript-loader/issues/561
目测是不能在.vue里面的<script>里面内嵌代码？

**Comment by WingGao** [comment]
是的，目前是这样的，然后定义组件完，然后引入的时候，尽量用'@/components/xxx.vue'这样的自定义路径的方式，目前`mpvue-loader`对ts支持不友好，只能劲量规避这种

**Comment by linfan68** [comment]
嗯我折腾了几天基本上放弃了……
虽然TS各种好，但是和mpvue这种新框架碰在一起对于我这种新手还真的是搞不定……昨天本来都弄好了，结果发现如果要用Vuex的话又不知道该怎么搞……只能果断放弃了

我估计先用babel把mpvue弄熟了再回来试试看……

**Comment by WingGao** [comment]
我刚刚尝试了用外部script的方式创建组件是可行，像这样https://github.com/WingGao/mpvue-ts-demo/commit/546d3ae0751bc8552c72120728fc9d3836b8f534

**Comment by linfan68** [comment]
嗯，这个方法我也试出来了，有了decorator还是很好用的！
目前blocker主要是vuex的store不知道该怎么加，我简单搜了一下没看到特别简单的方法，主要是还要给typescript做typesafe啥的。
你要是感觉那个approach可以follow的话可以给我些pointer我自己试一下。
